name: Trigger Site Rebuild on a CRON Schedule

on:
  schedule:
    # triggered at 9:16 expected at 9:09
    - cron: '39 3 * * *'
    
    # triggered at 10:11 expected at 9:51 am
    - cron: '21 4 * * *'
    - cron: '8 7 * * *'
jobs:
  build:
    name: Trigger build
    runs-on: ubuntu-latest
    steps:
      - name: run helloworld
  
        run: echo "hello-world"
